In [1]:
from dputils.scrape import Scraper, Tag

In [2]:
url = 'https://www.flipkart.com/motorola-edge-50-pro-5g-68w-charger-black-beauty-256-gb/p/itmb3f6625c5c896?pid=MOBGXFXYDG8YRZU4&lid=LSTMOBGXFXYDG8YRZU4SAX9WW&marketplace=FLIPKART&store=tyy%2F4io&srno=b_1_1&otracker=browse&fm=organic&iid=ace38f80-151a-41b0-a079-b620b88b8ec9.MOBGXFXYDG8YRZU4.SEARCH&ppt=hp&ppn=homepage&ssid=vj43l0oe680000001721542596100'
s1 = Scraper(url)

In [3]:
heading= Tag('h1', cls='_6EBuvT')
price = Tag(cls='Nx9bqj CxhGGd')
desc = Tag(cls='U+9u4y')
review = Tag(cls='RcXBOT')
results = s1.get_data_from_page(heading=heading, price=price, desc=desc, review=review)

In [4]:
items = Tag(cls='cPHDOP col-12-12')
url = "https://www.flipkart.com/tyy/4io/~cs-33irmtdz82/pr?sid=tyy%2C4io&collection-tab-name=Moto+Edge+50+pro+5g&param=279892&ctx=eyJjYXJkQ29udGV4dCI6eyJhdHRyaWJ1dGVzIjp7InZhbHVlQ2FsbG91dCI6eyJtdWx0aVZhbHVlZEF0dHJpYnV0ZSI6eyJrZXkiOiJ2YWx1ZUNhbGxvdXQiLCJpbmZlcmVuY2VUeXBlIjoiVkFMVUVfQ0FMTE9VVCIsInZhbHVlcyI6WyJGcm9tIOKCuTI3LDk5OSoiXSwidmFsdWVUeXBlIjoiTVVMVElfVkFMVUVEIn19LCJ0aXRsZSI6eyJtdWx0aVZhbHVlZEF0dHJpYnV0ZSI6eyJrZXkiOiJ0aXRsZSIsImluZmVyZW5jZVR5cGUiOiJUSVRMRSIsInZhbHVlcyI6WyJtb3Rvcm9sYSBlZGdlIDUwIFBybyJdLCJ2YWx1ZVR5cGUiOiJNVUxUSV9WQUxVRUQifX0sImhlcm9QaWQiOnsic2luZ2xlVmFsdWVBdHRyaWJ1dGUiOnsia2V5IjoiaGVyb1BpZCIsImluZmVyZW5jZVR5cGUiOiJQSUQiLCJ2YWx1ZSI6Ik1PQkdYRlhZTVRLQU1QVFMiLCJ2YWx1ZVR5cGUiOiJTSU5HTEVfVkFMVUVEIn19fX19"
s2 = Scraper(url)
results = s2.get_repeating_date_from_page(
    target = Tag('body'),
    items = items,
    title = Tag(cls='KzDlHZ'),
    price = Tag(cls='Nx9bqj _4b5DiR'),
    ratings = Tag('span', cls='Wphh3N')
)

In [5]:
import pandas as pd
pd.DataFrame(results)

,title,price,ratings
0,None,None,None
1,None,None,None
2,Motorola Edge 50 Pro 5G with 68W Charger (Blac...,"₹29,999","19,442 Ratings & 1,718 Reviews"
3,Motorola Edge 50 Pro 5G with 68W Charger (Luxe...,"₹29,999","19,442 Ratings & 1,718 Reviews"
4,Motorola Edge 50 Pro 5G with 125W Charger (Bla...,"₹34,999","6,966 Ratings & 591 Reviews"
5,Motorola Edge 50 Pro 5G with 125W Charger (Lux...,"₹34,999","6,966 Ratings & 591 Reviews"
6,Motorola Edge 50 Pro 5G with 125W Charger (Van...,"₹34,999","6,966 Ratings & 591 Reviews"
7,Motorola Edge 50 Pro 5G with 68W Charger (Moon...,"₹29,999","19,442 Ratings & 1,718 Reviews"
8,Motorola Edge 50 Pro 5G with 68W Charger (Vani...,"₹29,999","19,442 Ratings & 1,718 Reviews"
9,Motorola Edge 50 Pro 5G with 125W Charger (Moo...,"₹34,999","6,966 Ratings & 591 Reviews"
10,None,None,None
11,None,None,None

In [6]:
items = Tag(cls='s-result-item')
title = Tag('span', cls='a-size-base-plus a-color-base a-text-normal')
url ='https://www.amazon.in/s?k=shoes&crid=2OAOAMZS2EVJY&sprefix=shoe%2Caps%2C306&ref=nb_sb_noss_1'
s3 = Scraper(url)
results = s3.get_repeating_date_from_page(
    target = Tag('body'),
    items = items,
    title = title,
    brand = Tag('h2', cls='a-size-mini s-line-clamp-1')
)
pd.DataFrame(results).dropna()

                                                title   brand
2                         Men's AGR-004 Walking Shoes  Campus
3   Flash Casual Sneakers Riding Shoes for Men | S...  Campus
4   North Plus Sports Running Walking Gym Shoes fo...  Campus
5   Maxico Men's Running, Jogging, Gym, Sports, an...  Campus
6   Exclusive Trendy Sports Running Shoes | Casual...  BRUTON
..                                                ...     ...
64                      Mens Boss-Slick Formal Shoes,    Bata
65  First Running Walking Jogging Walking Gym Shoe...  Campus
66                           mens Wisdom Running Shoe  Campus
67                      Men's Tyson PRO Running Shoes  Campus
68  Men's MIKE (N) BRGNDY/WHT Running Shoes - 9UK/...  Campus

[66 rows x 2 columns]

In [ ]:
url=''

In [ ]:
from sqlachemy import create_engine,table,column,integer,string,DateTime
from sqlachemy import.orm  import Session , declarative_base
from datetime import datatime

Base = declarative_base()

class News (Base):
    __tablename__='news'
    id=column(integer,primary_key=True)
    title=column(string)
    content=column(string)
    posted_by=column(string)
    Image=column(string)
    created_at=column(DataFrame,default=DateTime.now) # auto timestamp